### ISSUE TITLE
無法選擇寶具卡

### ISSUE THREAD

**Issue by eight04** [mrbigmouth/fgo-simulator#1]
1. 我方選 3 名 NP 100 的從者
2. 選 3 張寶具卡
3. 點擊進入「暫時buff」修改頁面
4. 點擊取消
5. 寶具卡變成非選擇狀態且無法點擊

**Comment by mrbigmouth** [comment]
已修正

**Comment by eight04** [comment]
請問修正會直接反應在 https://mrbigmouth.github.io/fgo-simulator 上嗎？還是要過段時間。

**Comment by mrbigmouth** [comment]
修正時就已經在網頁上更新了喔，如果還有問題試著清一下網頁快取。

**Comment by eight04** [comment]
開新的 Profile 還是一樣。影片︰
![test](https://user-images.githubusercontent.com/1324510/35496350-c0524806-0500-11e8-88c7-35973bc5db55.gif)

Firefox Developer Edition 59.0b4

**Comment by mrbigmouth** [comment]
嗯....我只處理了「確認送出」之後的Bug，沒有處理到「取消」後的Bug。

現在都處理完畢了。
